SELECT TO_CHAR(DATE_TRUNC('month',CONVERSATION_START_DATE),'YYYY-MM') month,
  SUM(COUNT_TABANDON) abandon,
  SUM(COUNT_VOICE_NOFFERED)+SUM(COUNT_CALLBACK_NOFFERED) offered
FROM BI.PHONE_QUEUE_METRICS
WHERE ACD_QUEUE_NAME='Onboarding'
  AND CONVERSATION_START_DATE>='2026-01-01' AND CONVERSATION_START_DATE< DATEADD('day',1,CURRENT_DATE())
GROUP BY 1 ORDER BY 1
