-- OA per-IC per-month aggregation, aligned to canonical bo_grain_sla_v11.sql
WITH IC_EE_ID AS (
  -- resolve any historical owner SFDC user id -> current employee name (handles name changes)
  SELECT v1.SFDC_USER_ID, COALESCE(v2.NAME, v1.NAME) AS NAME
  FROM BI.SFDC_USERS_GUSTO_EMPLOYEES_VIEW v1
  LEFT JOIN BI.GUSTO_EMPLOYEES v2 ON v2.SFDC_EE_ID=v1.SFDC_EE_ID AND v2.CURRENT_FLAG=TRUE
  WHERE v1.SFDC_EE_ID <> 111883
  QUALIFY ROW_NUMBER() OVER (PARTITION BY v1.SFDC_USER_ID ORDER BY CASE WHEN v2.NAME IS NOT NULL THEN 0 ELSE 1 END, v1.SFDC_EE_ID)=1
),
BO_ATTRS AS (
  SELECT SFDC_BENEFIT_ORDER_ID, RECORD_TYPE_NAME, SFDC_BENEFIT_ORDER_OWNER_ID,
         CANCEL_FLAG, FULFILLED_FLAG,
         NVL(TOTAL_IMPLEMENTATION_ADVOCATE_TICKETS,0)+NVL(TOTAL_ER_OUTREACH_TICKETS,0) AS OA_MAPPED_TICKETS,
         CASE WHEN FULFILLED_FLAG=TRUE THEN FIRST_FULFILLED_TS WHEN CANCEL_FLAG=TRUE THEN FIRST_CANCEL_TS END AS FIRST_END_DT
  FROM BI_REPORTING.BENEFIT_ORDERS
  WHERE CONVERT_TIMEZONE('UTC','America/Denver',
          CASE WHEN FULFILLED_FLAG=TRUE THEN FIRST_FULFILLED_TS WHEN CANCEL_FLAG=TRUE THEN FIRST_CANCEL_TS END)
        BETWEEN '2026-01-01'::TIMESTAMP AND CURRENT_TIMESTAMP()
    AND RECORD_TYPE_NAME IN ('New Plan','Renewal','Change')
),
HIST AS (
  SELECT H.SFDC_OBJECT_ID, H.RECORD_TYPE, H.FROM_STATUS AS STATUS_NAME, H.START_TIME,
         COALESCE(H.END_TIME,CURRENT_DATE) AS END_TIME, COALESCE(H.DURATION_IN_MINS,0) AS DURATION_IN_MINS
  FROM BI.BENEFIT_ORDER_STATUS_CHANGE_HISTORY H
  INNER JOIN BO_ATTRS A ON H.SFDC_OBJECT_ID=A.SFDC_BENEFIT_ORDER_ID
  WHERE H.RECORD_TYPE IN ('New Plan','Renewal','Change')
    AND H.FROM_STATUS IN ('Ready for OE Prep','OE Verification/Checking Participation','ER Outreach Required','Awaiting Routing','Approved','Blocked','With Sales','With Advising','Awaiting ER Response - Pending Item','OE','OE Extended')
),
LAGGED AS (
  SELECT H.*, LAG(STATUS_NAME) OVER (PARTITION BY SFDC_OBJECT_ID,RECORD_TYPE ORDER BY START_TIME) AS LAG_STATUS,
         LAG(END_TIME) OVER (PARTITION BY SFDC_OBJECT_ID,RECORD_TYPE ORDER BY START_TIME) AS LAG_END
  FROM HIST H
),
FLAGGED AS (
  SELECT *, CASE WHEN LAG_STATUS=STATUS_NAME AND ABS(DATEDIFF('DAY',LAG_END,START_TIME))<=1 THEN 0 ELSE 1 END AS IS_NEW_GROUP
  FROM LAGGED
),
GROUPED AS (
  SELECT *, SUM(IS_NEW_GROUP) OVER (PARTITION BY SFDC_OBJECT_ID,RECORD_TYPE ORDER BY START_TIME ROWS UNBOUNDED PRECEDING) AS GRP
  FROM FLAGGED
),
STINTS AS (
  SELECT SFDC_OBJECT_ID, RECORD_TYPE, STATUS_NAME, ROUND(SUM(DURATION_IN_MINS)::FLOAT/1440,3) AS STINT_DAYS
  FROM GROUPED GROUP BY SFDC_OBJECT_ID,RECORD_TYPE,STATUS_NAME,GRP HAVING SUM(DURATION_IN_MINS)>0
),
BO_STATUS AS (
  SELECT SFDC_OBJECT_ID, STATUS_NAME, SUM(STINT_DAYS) AS TOTAL_DAYS,
         CASE WHEN SUM(STINT_DAYS)<=1 THEN 1 ELSE 0 END AS SLA_MET
  FROM STINTS GROUP BY SFDC_OBJECT_ID,STATUS_NAME
),
OA_HELD AS (
  SELECT SFDC_OBJECT_ID,
    -- ENTERED_OA=1 iff the order actually went through >=1 of the 5 scored OA-held stages.
    -- Gates the denominator to entered-OA orders (matches Advising 'scored' + Broker 'entered statuses only').
    MAX(CASE WHEN STATUS_NAME IN ('Ready for OE Prep','OE Verification/Checking Participation',
                                  'ER Outreach Required','Awaiting Routing','Approved')
             THEN 1 ELSE 0 END) AS ENTERED_OA,
    LEAST(
      COALESCE(MAX(CASE WHEN STATUS_NAME='Ready for OE Prep' THEN SLA_MET END),1),
      COALESCE(MAX(CASE WHEN STATUS_NAME='OE Verification/Checking Participation' THEN SLA_MET END),1),
      COALESCE(MAX(CASE WHEN STATUS_NAME='ER Outreach Required' THEN SLA_MET END),1),
      COALESCE(MAX(CASE WHEN STATUS_NAME='Awaiting Routing' THEN SLA_MET END),1),
      COALESCE(MAX(CASE WHEN STATUS_NAME='Approved' THEN SLA_MET END),1)
    ) AS WITH_OA_MET
  FROM BO_STATUS GROUP BY SFDC_OBJECT_ID
)
SELECT ee.NAME ic, TO_CHAR(DATE_TRUNC('month',CONVERT_TIMEZONE('UTC','America/Denver',A.FIRST_END_DT)),'YYYY-MM') month,
  COUNT(*) orders,
  SUM(IFF(A.RECORD_TYPE_NAME='New Plan',1,0)) np_orders,
  SUM(IFF(A.RECORD_TYPE_NAME='New Plan' AND A.CANCEL_FLAG,1,0)) np_cancels,
  SUM(IFF(A.RECORD_TYPE_NAME='New Plan' AND A.FULFILLED_FLAG AND NOT A.CANCEL_FLAG,1,0)) np_ful,
  SUM(IFF(A.RECORD_TYPE_NAME='New Plan' AND A.FULFILLED_FLAG AND NOT A.CANCEL_FLAG AND A.OA_MAPPED_TICKETS>0,1,0)) np_ful_tkt,
  SUM(IFF(A.RECORD_TYPE_NAME IN ('Renewal','Change') AND A.FULFILLED_FLAG AND NOT A.CANCEL_FLAG,1,0)) rn_ful,
  SUM(IFF(A.RECORD_TYPE_NAME IN ('Renewal','Change') AND A.FULFILLED_FLAG AND NOT A.CANCEL_FLAG AND A.OA_MAPPED_TICKETS>0,1,0)) rn_ful_tkt,
  SUM(IFF(A.RECORD_TYPE_NAME='New Plan' AND A.FULFILLED_FLAG AND NOT A.CANCEL_FLAG, A.OA_MAPPED_TICKETS, 0)) np_tkt_sum,
  SUM(IFF(A.RECORD_TYPE_NAME IN ('Renewal','Change') AND A.FULFILLED_FLAG AND NOT A.CANCEL_FLAG, A.OA_MAPPED_TICKETS, 0)) rn_tkt_sum,
  -- Denominator = closed (fulfilled + cancelled) orders that ENTERED >=1 scored OA stage (gated, matches Advising/Broker).
  SUM(IFF(O.ENTERED_OA=1,1,0)) oa_elig_n,
  SUM(IFF(O.ENTERED_OA=1 AND O.WITH_OA_MET=1,1,0)) oa_pass_n
FROM BO_ATTRS A
JOIN IC_EE_ID ee ON A.SFDC_BENEFIT_ORDER_OWNER_ID=ee.SFDC_USER_ID
LEFT JOIN OA_HELD O ON A.SFDC_BENEFIT_ORDER_ID=O.SFDC_OBJECT_ID
GROUP BY 1,2
ORDER BY 1,2
