WITH IC_EE_ID AS (
  SELECT v1.SFDC_USER_ID, COALESCE(v2.NAME,v1.NAME) AS NAME
  FROM BI.SFDC_USERS_GUSTO_EMPLOYEES_VIEW v1
  LEFT JOIN BI.GUSTO_EMPLOYEES v2 ON v2.SFDC_EE_ID=v1.SFDC_EE_ID AND v2.CURRENT_FLAG=TRUE
  WHERE v1.SFDC_EE_ID <> 111883
  QUALIFY ROW_NUMBER() OVER (PARTITION BY v1.SFDC_USER_ID ORDER BY CASE WHEN v2.NAME IS NOT NULL THEN 0 ELSE 1 END, v1.SFDC_EE_ID)=1
),
OA AS (SELECT NAME FROM BI.GUSTO_EMPLOYEES WHERE CURRENT_FLAG=TRUE AND STATUS IN ('Active','On Leave')
  AND SUB_TEAM IN ('New Plan & Renewal Onboarding','Onboarding Advocacy') AND IS_PE=FALSE)
SELECT ee.NAME AS IC, TO_CHAR(DATE_TRUNC('month',c.TYPEFORM_SUBMITTED_AT),'YYYY-MM') AS MONTH,
  c.CSAT_SCORE AS SCORE, c.TYPEFORM_SUBMITTED_AT::date AS DT, bo.RECORD_TYPE_NAME AS RT,
  LEFT(NVL(c.COMMENT,''),300) AS COMMENT
FROM BI_REPORTING.CES_CSAT_DATA c
JOIN BI_REPORTING.BENEFIT_ORDERS bo ON bo.SFDC_BENEFIT_ORDER_ID=c.SFDC_ONBOARDING_OBJECT_ID
JOIN IC_EE_ID ee ON bo.SFDC_BENEFIT_ORDER_OWNER_ID=ee.SFDC_USER_ID
JOIN OA ON OA.NAME=ee.NAME
WHERE c.TYPEFORM_SUBMITTED_AT BETWEEN '2026-01-01' AND CURRENT_DATE()
  AND bo.RECORD_TYPE_NAME IN ('New Plan','Renewal') AND c.CSAT_SCORE IS NOT NULL
ORDER BY ee.NAME, DT
