WITH price_book AS (
  SELECT 'medical_fully_insured' AS pk, 33.24::FLOAT AS up UNION ALL
  SELECT 'medical_level_funded'  AS pk, 46.53::FLOAT AS up UNION ALL
  SELECT 'dental' AS pk, 6.58::FLOAT AS up UNION ALL
  SELECT 'vision' AS pk, 1.20::FLOAT AS up UNION ALL
  SELECT 'life' AS pk, 1.21::FLOAT AS up UNION ALL
  SELECT 'long_term_disability' AS pk, 1.65::FLOAT AS up UNION ALL
  SELECT 'short_term_disability' AS pk, 1.82::FLOAT AS up UNION ALL
  SELECT 'fsa' AS pk, 4.00::FLOAT AS up UNION ALL
  SELECT 'dca' AS pk, 4.00::FLOAT AS up UNION ALL
  SELECT 'hsa' AS pk, 2.50::FLOAT AS up UNION ALL
  SELECT 'voluntary_life' AS pk, 5.28::FLOAT AS up UNION ALL
  SELECT 'voluntary_long_term_disability' AS pk, 5.28::FLOAT AS up UNION ALL
  SELECT 'voluntary_short_term_disability' AS pk, 5.28::FLOAT AS up
),
opp AS (
  SELECT * FROM BI_REPORTING.ADVISING_OPPORTUNITIES
  WHERE RENEWAL_DATE BETWEEN DATEADD('year',-1,'{{Close Start}}'::DATE) AND DATEADD('year',1,'{{Close End}}'::DATE)
),
base AS (
  SELECT SFDC_OBJECT_ID, SFDC_OBJECT_NAME_OR_NUM, HI_RENEWAL_ID, ZP_COMPANY_ID, SFDC_ACCOUNT_ID,
    STATUS, STAGE_DETAIL, REASON_FOR_ADVISING, OWNER_NAME, OPPORTUNITY_OWNER_PE_NAME,
    RENEWAL_DATE, FUNDING_TYPE,
    ACTIVE_EMPLOYEES_BEFORE, BENEFITS_ELIGIBLE_EMPLOYEES_BEFORE, NUMBER_EMPLOYEES_ENROLLED_BEFORE,
    ACTIVE_EMPLOYEES_AFTER,  BENEFITS_ELIGIBLE_EMPLOYEES_AFTER,  NUMBER_EMPLOYEES_ENROLLED_AFTER,
    HAS_MEDICAL_BEFORE, HAS_MEDICAL_AFTER, HAS_DENTAL_BEFORE, HAS_DENTAL_AFTER,
    HAS_VISION_BEFORE,  HAS_VISION_AFTER,  HAS_LIFE_BEFORE,   HAS_LIFE_AFTER,
    HAS_LTD_BEFORE,     HAS_LTD_AFTER,     HAS_STD_BEFORE,    HAS_STD_AFTER,
    HAS_FSA_BEFORE,     HAS_FSA_AFTER,     HAS_DCA_BEFORE,    HAS_DCA_AFTER,
    HAS_HSA_BEFORE,     HAS_HSA_AFTER
  FROM opp
),
loss_history AS (
  SELECT OPPORTUNITY_ID, CLOSE_DATE AS LOSS_CLOSE_DATE
  FROM BI.SFDC_OPPORTUNITY_HISTORY
  WHERE STAGENAME ILIKE '%closed lost%' OR STAGENAME ILIKE '%order lost%'
  QUALIFY ROW_NUMBER() OVER (PARTITION BY OPPORTUNITY_ID ORDER BY EFFECT_START_DT DESC, ETL_UPDATE_TS DESC) = 1
),
bo_rollup AS (
  SELECT SFDC_OPPORTUNITY_ID,
    MAX(IFF(FULFILLED_FLAG, LAST_FULFILLED_TS, NULL)) AS BO_LAST_FULFILLED_TS
  FROM BI_REPORTING.BENEFIT_ORDERS WHERE SFDC_OPPORTUNITY_ID IS NOT NULL GROUP BY 1
),
opp_enriched AS (
  SELECT b.*, bo.BO_LAST_FULFILLED_TS, DATE(bo.BO_LAST_FULFILLED_TS) AS FULFILLED_DATE,
    CASE
      WHEN b.STATUS ILIKE '%closed won%' THEN DATE(bo.BO_LAST_FULFILLED_TS)
      WHEN b.STATUS ILIKE '%closed lost%' OR b.STATUS ILIKE '%order lost%' THEN lh.LOSS_CLOSE_DATE
      ELSE NULL
    END AS INFERRED_CLOSE_DATE
  FROM base b
  LEFT JOIN bo_rollup bo ON b.SFDC_OBJECT_ID = bo.SFDC_OPPORTUNITY_ID
  LEFT JOIN loss_history lh ON b.SFDC_OBJECT_ID = lh.OPPORTUNITY_ID
),
ol AS (
  SELECT o.SFDC_OBJECT_ID, o.RENEWAL_DATE, p.policy_id, p.benefit_type, p.renewal_stage_name, p.carrier_name
  FROM opp_enriched o
  JOIN BI.FCT_HEALTH_INSURANCE_RENEWAL_LIFECYCLE p ON o.HI_RENEWAL_ID = p.renewal_id
  WHERE p.renewal_stage_name IN ('expiring','selected')
),
sb_long AS (
  SELECT ol.SFDC_OBJECT_ID, ol.benefit_type, COUNT(DISTINCT s.hi_employee_id) AS enr
  FROM ol JOIN BI.DIM_HEALTH_INSURANCE_SUBSCRIPTION s
    ON ol.policy_id = s.policy_id AND DATEADD('day',-105,ol.RENEWAL_DATE) BETWEEN s.start_date AND s.end_date
  WHERE ol.renewal_stage_name='expiring' GROUP BY 1,2
),
sa_long AS (
  SELECT ol.SFDC_OBJECT_ID, ol.benefit_type, COUNT(DISTINCT s.hi_employee_id) AS enr
  FROM ol JOIN BI.DIM_HEALTH_INSURANCE_SUBSCRIPTION s
    ON ol.policy_id = s.policy_id AND s.start_date BETWEEN DATEADD('day',-30,ol.RENEWAL_DATE) AND DATEADD('day',30,ol.RENEWAL_DATE)
  WHERE ol.renewal_stage_name='selected' GROUP BY 1,2
),
vh AS (
  SELECT ol.SFDC_OBJECT_ID,
    MAX(IFF(benefit_type='voluntary_life' AND renewal_stage_name='expiring',1,0))::BOOLEAN AS HAS_VLIFE_BEFORE,
    MAX(IFF(benefit_type='voluntary_life' AND renewal_stage_name='selected',1,0))::BOOLEAN AS HAS_VLIFE_AFTER,
    MAX(IFF(benefit_type='voluntary_long_term_disability' AND renewal_stage_name='expiring',1,0))::BOOLEAN AS HAS_VLTD_BEFORE,
    MAX(IFF(benefit_type='voluntary_long_term_disability' AND renewal_stage_name='selected',1,0))::BOOLEAN AS HAS_VLTD_AFTER,
    MAX(IFF(benefit_type='voluntary_short_term_disability' AND renewal_stage_name='expiring',1,0))::BOOLEAN AS HAS_VSTD_BEFORE,
    MAX(IFF(benefit_type='voluntary_short_term_disability' AND renewal_stage_name='selected',1,0))::BOOLEAN AS HAS_VSTD_AFTER
  FROM ol GROUP BY 1
),
sb AS (
  SELECT SFDC_OBJECT_ID,
    MAX(IFF(benefit_type='medical', enr, NULL)) AS ENROLLED_MEDICAL_BEFORE,
    MAX(IFF(benefit_type='dental', enr, NULL)) AS ENROLLED_DENTAL_BEFORE,
    MAX(IFF(benefit_type='vision', enr, NULL)) AS ENROLLED_VISION_BEFORE,
    MAX(IFF(benefit_type='life', enr, NULL)) AS ENROLLED_LIFE_BEFORE,
    MAX(IFF(benefit_type='long_term_disability', enr, NULL)) AS ENROLLED_LTD_BEFORE,
    MAX(IFF(benefit_type='short_term_disability', enr, NULL)) AS ENROLLED_STD_BEFORE,
    MAX(IFF(benefit_type='fsa', enr, NULL)) AS ENROLLED_FSA_BEFORE,
    MAX(IFF(benefit_type='dca', enr, NULL)) AS ENROLLED_DCA_BEFORE,
    MAX(IFF(benefit_type='hsa', enr, NULL)) AS ENROLLED_HSA_BEFORE,
    MAX(IFF(benefit_type='voluntary_life', enr, NULL)) AS ENROLLED_VLIFE_BEFORE,
    MAX(IFF(benefit_type='voluntary_long_term_disability', enr, NULL)) AS ENROLLED_VLTD_BEFORE,
    MAX(IFF(benefit_type='voluntary_short_term_disability', enr, NULL)) AS ENROLLED_VSTD_BEFORE
  FROM sb_long GROUP BY 1
),
sa AS (
  SELECT SFDC_OBJECT_ID,
    MAX(IFF(benefit_type='medical', enr, NULL)) AS ENROLLED_MEDICAL_AFTER,
    MAX(IFF(benefit_type='dental', enr, NULL)) AS ENROLLED_DENTAL_AFTER,
    MAX(IFF(benefit_type='vision', enr, NULL)) AS ENROLLED_VISION_AFTER,
    MAX(IFF(benefit_type='life', enr, NULL)) AS ENROLLED_LIFE_AFTER,
    MAX(IFF(benefit_type='long_term_disability', enr, NULL)) AS ENROLLED_LTD_AFTER,
    MAX(IFF(benefit_type='short_term_disability', enr, NULL)) AS ENROLLED_STD_AFTER,
    MAX(IFF(benefit_type='fsa', enr, NULL)) AS ENROLLED_FSA_AFTER,
    MAX(IFF(benefit_type='dca', enr, NULL)) AS ENROLLED_DCA_AFTER,
    MAX(IFF(benefit_type='hsa', enr, NULL)) AS ENROLLED_HSA_AFTER,
    MAX(IFF(benefit_type='voluntary_life', enr, NULL)) AS ENROLLED_VLIFE_AFTER,
    MAX(IFF(benefit_type='voluntary_long_term_disability', enr, NULL)) AS ENROLLED_VLTD_AFTER,
    MAX(IFF(benefit_type='voluntary_short_term_disability', enr, NULL)) AS ENROLLED_VSTD_AFTER
  FROM sa_long GROUP BY 1
),
carr_raw AS ( -- per opp x line x carrier enrolled, both windows (insured lines only)
  SELECT ol.SFDC_OBJECT_ID, ol.benefit_type,
    IFF(ol.renewal_stage_name='expiring','b','a') AS stg,
    s.carrier_name AS carrier, COALESCE(s.carrier_state,'') AS st,
    COUNT(DISTINCT s.hi_employee_id) AS enr
  FROM ol
  JOIN BI.DIM_HEALTH_INSURANCE_SUBSCRIPTION s
    ON ol.policy_id = s.policy_id
   AND ( (ol.renewal_stage_name='expiring' AND DATEADD('day',-105,ol.RENEWAL_DATE) BETWEEN s.start_date AND s.end_date)
      OR (ol.renewal_stage_name='selected' AND s.start_date BETWEEN DATEADD('day',-30,ol.RENEWAL_DATE) AND DATEADD('day',30,ol.RENEWAL_DATE)) )
  WHERE s.carrier_name IS NOT NULL
  GROUP BY 1,2,3,4,5
),
sub_present AS ( -- opp x line x stage that already have a subscription-derived carrier
  SELECT DISTINCT SFDC_OBJECT_ID, benefit_type, stg FROM carr_raw
),
pol_fill AS ( -- policy carrier from lifecycle, ONLY where no subscription carrier exists (gap-fill, enr=0)
  SELECT ol.SFDC_OBJECT_ID, ol.benefit_type,
    IFF(ol.renewal_stage_name='expiring','b','a') AS stg,
    ol.carrier_name AS carrier, COALESCE(pol.carrier_state_code,'') AS st, 0 AS enr
  FROM ol
  LEFT JOIN sub_present sp
    ON sp.SFDC_OBJECT_ID = ol.SFDC_OBJECT_ID
   AND sp.benefit_type   = ol.benefit_type
   AND sp.stg            = IFF(ol.renewal_stage_name='expiring','b','a')
  LEFT JOIN BI.DIM_HEALTH_INSURANCE_POLICY pol ON pol.policy_id = ol.policy_id
  WHERE ol.carrier_name IS NOT NULL AND sp.SFDC_OBJECT_ID IS NULL
    AND ol.benefit_type IN ('medical','dental','vision','life','long_term_disability','short_term_disability','voluntary_life','voluntary_long_term_disability','voluntary_short_term_disability')
  GROUP BY 1,2,3,4,5,6
),
carr_all AS ( -- subscription carriers + policy gap-fills
  SELECT SFDC_OBJECT_ID, benefit_type, stg, carrier, st, enr FROM carr_raw
  UNION ALL
  SELECT SFDC_OBJECT_ID, benefit_type, stg, carrier, st, enr FROM pol_fill
),
carr_line AS ( -- collapse to one object per opp x line: {b:[{c,s,e}], a:[{c,s,e}]}
  SELECT SFDC_OBJECT_ID, benefit_type,
    OBJECT_CONSTRUCT(
      'b', ARRAY_COMPACT(ARRAY_AGG(IFF(stg='b', OBJECT_CONSTRUCT('c',carrier,'s',st,'e',enr), NULL))),
      'a', ARRAY_COMPACT(ARRAY_AGG(IFF(stg='a', OBJECT_CONSTRUCT('c',carrier,'s',st,'e',enr), NULL)))
    ) AS line_obj
  FROM carr_all
  GROUP BY 1,2
),
carr_json AS ( -- one row per opp: object keyed by benefit_type (display-only, no fan-out)
  SELECT SFDC_OBJECT_ID, OBJECT_AGG(benefit_type, line_obj) AS carrier_detail
  FROM carr_line
  GROUP BY 1
),
med_fund AS (
  SELECT o.SFDC_OBJECT_ID,
    MAX(IFF(p.renewal_stage_name='expiring', bp.funding_type, NULL)) AS before_fund,
    MAX(IFF(p.renewal_stage_name='selected', bp.funding_type, NULL)) AS after_fund
  FROM opp_enriched o
  JOIN BI.FCT_HEALTH_INSURANCE_RENEWAL_LIFECYCLE p ON o.HI_RENEWAL_ID = p.renewal_id AND p.benefit_type='medical'
  JOIN HAWAIIAN_ICE_PRODUCTION_NO_PII.BENEFITS_PLANS bp ON bp.id = p.benefits_plan_id
  WHERE p.renewal_stage_name IN ('expiring','selected')
  GROUP BY 1
),
calc AS (
  SELECT o.*,
    cj.carrier_detail,
    mf.before_fund, mf.after_fund,
    sb.ENROLLED_MEDICAL_BEFORE, sb.ENROLLED_DENTAL_BEFORE, sb.ENROLLED_VISION_BEFORE,
    sb.ENROLLED_LIFE_BEFORE, sb.ENROLLED_LTD_BEFORE, sb.ENROLLED_STD_BEFORE,
    sb.ENROLLED_FSA_BEFORE, sb.ENROLLED_DCA_BEFORE, sb.ENROLLED_HSA_BEFORE,
    sb.ENROLLED_VLIFE_BEFORE, sb.ENROLLED_VLTD_BEFORE, sb.ENROLLED_VSTD_BEFORE,
    sa.ENROLLED_MEDICAL_AFTER, sa.ENROLLED_DENTAL_AFTER, sa.ENROLLED_VISION_AFTER,
    sa.ENROLLED_LIFE_AFTER, sa.ENROLLED_LTD_AFTER, sa.ENROLLED_STD_AFTER,
    sa.ENROLLED_FSA_AFTER, sa.ENROLLED_DCA_AFTER, sa.ENROLLED_HSA_AFTER,
    sa.ENROLLED_VLIFE_AFTER, sa.ENROLLED_VLTD_AFTER, sa.ENROLLED_VSTD_AFTER,
    COALESCE(vh.HAS_VLIFE_BEFORE, FALSE) AS HAS_VLIFE_BEFORE,
    COALESCE(vh.HAS_VLIFE_AFTER,  FALSE) AS HAS_VLIFE_AFTER,
    COALESCE(vh.HAS_VLTD_BEFORE,  FALSE) AS HAS_VLTD_BEFORE,
    COALESCE(vh.HAS_VLTD_AFTER,   FALSE) AS HAS_VLTD_AFTER,
    COALESCE(vh.HAS_VSTD_BEFORE,  FALSE) AS HAS_VSTD_BEFORE,
    COALESCE(vh.HAS_VSTD_AFTER,   FALSE) AS HAS_VSTD_AFTER,
    CASE WHEN NOT o.HAS_MEDICAL_BEFORE THEN 0
      WHEN LOWER(COALESCE(mf.before_fund, o.FUNDING_TYPE,'')) LIKE '%level%' THEN sb.ENROLLED_MEDICAL_BEFORE * 46.53
      ELSE sb.ENROLLED_MEDICAL_BEFORE * 33.24 END AS MRR_MEDICAL_BEFORE,
    CASE WHEN NOT o.HAS_DENTAL_BEFORE THEN 0 ELSE sb.ENROLLED_DENTAL_BEFORE * 6.58 END AS MRR_DENTAL_BEFORE,
    CASE WHEN NOT o.HAS_VISION_BEFORE THEN 0 ELSE sb.ENROLLED_VISION_BEFORE * 1.20 END AS MRR_VISION_BEFORE,
    CASE WHEN NOT o.HAS_LIFE_BEFORE THEN 0 ELSE sb.ENROLLED_LIFE_BEFORE * 1.21 END AS MRR_LIFE_BEFORE,
    CASE WHEN NOT o.HAS_LTD_BEFORE THEN 0 ELSE sb.ENROLLED_LTD_BEFORE * 1.65 END AS MRR_LTD_BEFORE,
    CASE WHEN NOT o.HAS_STD_BEFORE THEN 0 ELSE sb.ENROLLED_STD_BEFORE * 1.82 END AS MRR_STD_BEFORE,
    CASE WHEN NOT o.HAS_FSA_BEFORE THEN 0 ELSE sb.ENROLLED_FSA_BEFORE * 4.00 END AS MRR_FSA_BEFORE,
    CASE WHEN NOT o.HAS_DCA_BEFORE THEN 0 ELSE sb.ENROLLED_DCA_BEFORE * 4.00 END AS MRR_DCA_BEFORE,
    CASE WHEN NOT o.HAS_HSA_BEFORE THEN 0 WHEN sb.ENROLLED_HSA_BEFORE IS NULL THEN NULL ELSE sb.ENROLLED_HSA_BEFORE * 2.50 END AS MRR_HSA_BEFORE,
    CASE WHEN NOT COALESCE(vh.HAS_VLIFE_BEFORE,FALSE) THEN 0 ELSE sb.ENROLLED_VLIFE_BEFORE * 5.28 END AS MRR_VLIFE_BEFORE,
    CASE WHEN NOT COALESCE(vh.HAS_VLTD_BEFORE,FALSE) THEN 0 ELSE sb.ENROLLED_VLTD_BEFORE * 5.28 END AS MRR_VLTD_BEFORE,
    CASE WHEN NOT COALESCE(vh.HAS_VSTD_BEFORE,FALSE) THEN 0 ELSE sb.ENROLLED_VSTD_BEFORE * 5.28 END AS MRR_VSTD_BEFORE,
    CASE WHEN o.FULFILLED_DATE IS NULL THEN NULL WHEN NOT o.HAS_MEDICAL_AFTER THEN 0
      WHEN LOWER(COALESCE(mf.after_fund, o.FUNDING_TYPE,'')) LIKE '%level%' THEN sa.ENROLLED_MEDICAL_AFTER * 46.53
      ELSE sa.ENROLLED_MEDICAL_AFTER * 33.24 END AS MRR_MEDICAL_AFTER,
    CASE WHEN o.FULFILLED_DATE IS NULL THEN NULL WHEN NOT o.HAS_DENTAL_AFTER THEN 0 ELSE sa.ENROLLED_DENTAL_AFTER * 6.58 END AS MRR_DENTAL_AFTER,
    CASE WHEN o.FULFILLED_DATE IS NULL THEN NULL WHEN NOT o.HAS_VISION_AFTER THEN 0 ELSE sa.ENROLLED_VISION_AFTER * 1.20 END AS MRR_VISION_AFTER,
    CASE WHEN o.FULFILLED_DATE IS NULL THEN NULL WHEN NOT o.HAS_LIFE_AFTER THEN 0 ELSE sa.ENROLLED_LIFE_AFTER * 1.21 END AS MRR_LIFE_AFTER,
    CASE WHEN o.FULFILLED_DATE IS NULL THEN NULL WHEN NOT o.HAS_LTD_AFTER THEN 0 ELSE sa.ENROLLED_LTD_AFTER * 1.65 END AS MRR_LTD_AFTER,
    CASE WHEN o.FULFILLED_DATE IS NULL THEN NULL WHEN NOT o.HAS_STD_AFTER THEN 0 ELSE sa.ENROLLED_STD_AFTER * 1.82 END AS MRR_STD_AFTER,
    CASE WHEN o.FULFILLED_DATE IS NULL THEN NULL WHEN NOT o.HAS_FSA_AFTER THEN 0 ELSE sa.ENROLLED_FSA_AFTER * 4.00 END AS MRR_FSA_AFTER,
    CASE WHEN o.FULFILLED_DATE IS NULL THEN NULL WHEN NOT o.HAS_DCA_AFTER THEN 0 ELSE sa.ENROLLED_DCA_AFTER * 4.00 END AS MRR_DCA_AFTER,
    CASE WHEN o.FULFILLED_DATE IS NULL THEN NULL WHEN NOT o.HAS_HSA_AFTER THEN 0 WHEN sa.ENROLLED_HSA_AFTER IS NULL THEN NULL ELSE sa.ENROLLED_HSA_AFTER * 2.50 END AS MRR_HSA_AFTER,
    CASE WHEN o.FULFILLED_DATE IS NULL THEN NULL WHEN NOT COALESCE(vh.HAS_VLIFE_AFTER,FALSE) THEN 0 ELSE sa.ENROLLED_VLIFE_AFTER * 5.28 END AS MRR_VLIFE_AFTER,
    CASE WHEN o.FULFILLED_DATE IS NULL THEN NULL WHEN NOT COALESCE(vh.HAS_VLTD_AFTER,FALSE) THEN 0 ELSE sa.ENROLLED_VLTD_AFTER * 5.28 END AS MRR_VLTD_AFTER,
    CASE WHEN o.FULFILLED_DATE IS NULL THEN NULL WHEN NOT COALESCE(vh.HAS_VSTD_AFTER,FALSE) THEN 0 ELSE sa.ENROLLED_VSTD_AFTER * 5.28 END AS MRR_VSTD_AFTER
  FROM opp_enriched o
  LEFT JOIN med_fund mf ON o.SFDC_OBJECT_ID = mf.SFDC_OBJECT_ID
  LEFT JOIN sb ON o.SFDC_OBJECT_ID = sb.SFDC_OBJECT_ID
  LEFT JOIN sa ON o.SFDC_OBJECT_ID = sa.SFDC_OBJECT_ID
  LEFT JOIN vh ON o.SFDC_OBJECT_ID = vh.SFDC_OBJECT_ID
  LEFT JOIN carr_json cj ON o.SFDC_OBJECT_ID = cj.SFDC_OBJECT_ID
)
SELECT
  STATUS, RENEWAL_DATE, INFERRED_CLOSE_DATE,
  (COALESCE(MRR_MEDICAL_BEFORE,0)+COALESCE(MRR_DENTAL_BEFORE,0)+COALESCE(MRR_VISION_BEFORE,0)
   +COALESCE(MRR_LIFE_BEFORE,0)+COALESCE(MRR_LTD_BEFORE,0)+COALESCE(MRR_STD_BEFORE,0)
   +COALESCE(MRR_FSA_BEFORE,0)+COALESCE(MRR_DCA_BEFORE,0)+COALESCE(MRR_HSA_BEFORE,0)
   +COALESCE(MRR_VLIFE_BEFORE,0)+COALESCE(MRR_VLTD_BEFORE,0)+COALESCE(MRR_VSTD_BEFORE,0))::FLOAT AS MRR_TOTAL_BEFORE,
  IFF(FULFILLED_DATE IS NULL, NULL,
   (COALESCE(MRR_MEDICAL_AFTER,0)+COALESCE(MRR_DENTAL_AFTER,0)+COALESCE(MRR_VISION_AFTER,0)
   +COALESCE(MRR_LIFE_AFTER,0)+COALESCE(MRR_LTD_AFTER,0)+COALESCE(MRR_STD_AFTER,0)
   +COALESCE(MRR_FSA_AFTER,0)+COALESCE(MRR_DCA_AFTER,0)+COALESCE(MRR_HSA_AFTER,0)
   +COALESCE(MRR_VLIFE_AFTER,0)+COALESCE(MRR_VLTD_AFTER,0)+COALESCE(MRR_VSTD_AFTER,0))::FLOAT) AS MRR_TOTAL_AFTER,
  (IFF(FULFILLED_DATE IS NULL, NULL,
   (COALESCE(MRR_MEDICAL_AFTER,0)+COALESCE(MRR_DENTAL_AFTER,0)+COALESCE(MRR_VISION_AFTER,0)
   +COALESCE(MRR_LIFE_AFTER,0)+COALESCE(MRR_LTD_AFTER,0)+COALESCE(MRR_STD_AFTER,0)
   +COALESCE(MRR_FSA_AFTER,0)+COALESCE(MRR_DCA_AFTER,0)+COALESCE(MRR_HSA_AFTER,0)
   +COALESCE(MRR_VLIFE_AFTER,0)+COALESCE(MRR_VLTD_AFTER,0)+COALESCE(MRR_VSTD_AFTER,0))::FLOAT)
   - (COALESCE(MRR_MEDICAL_BEFORE,0)+COALESCE(MRR_DENTAL_BEFORE,0)+COALESCE(MRR_VISION_BEFORE,0)
   +COALESCE(MRR_LIFE_BEFORE,0)+COALESCE(MRR_LTD_BEFORE,0)+COALESCE(MRR_STD_BEFORE,0)
   +COALESCE(MRR_FSA_BEFORE,0)+COALESCE(MRR_DCA_BEFORE,0)+COALESCE(MRR_HSA_BEFORE,0)
   +COALESCE(MRR_VLIFE_BEFORE,0)+COALESCE(MRR_VLTD_BEFORE,0)+COALESCE(MRR_VSTD_BEFORE,0))) AS DELTA_MRR_TOTAL,
  OWNER_NAME, OPPORTUNITY_OWNER_PE_NAME AS PE, SFDC_OBJECT_NAME_OR_NUM, STAGE_DETAIL, REASON_FOR_ADVISING, SFDC_OBJECT_ID, ZP_COMPANY_ID, FUNDING_TYPE, BEFORE_FUND, AFTER_FUND,
  ACTIVE_EMPLOYEES_BEFORE, ACTIVE_EMPLOYEES_AFTER,
  BENEFITS_ELIGIBLE_EMPLOYEES_BEFORE, BENEFITS_ELIGIBLE_EMPLOYEES_AFTER,
  NUMBER_EMPLOYEES_ENROLLED_BEFORE, NUMBER_EMPLOYEES_ENROLLED_AFTER,
  HAS_MEDICAL_BEFORE, HAS_MEDICAL_AFTER, ENROLLED_MEDICAL_BEFORE, ENROLLED_MEDICAL_AFTER, MRR_MEDICAL_BEFORE, MRR_MEDICAL_AFTER,
  HAS_DENTAL_BEFORE, HAS_DENTAL_AFTER, ENROLLED_DENTAL_BEFORE, ENROLLED_DENTAL_AFTER, MRR_DENTAL_BEFORE, MRR_DENTAL_AFTER,
  HAS_VISION_BEFORE, HAS_VISION_AFTER, ENROLLED_VISION_BEFORE, ENROLLED_VISION_AFTER, MRR_VISION_BEFORE, MRR_VISION_AFTER,
  HAS_LIFE_BEFORE, HAS_LIFE_AFTER, ENROLLED_LIFE_BEFORE, ENROLLED_LIFE_AFTER, MRR_LIFE_BEFORE, MRR_LIFE_AFTER,
  HAS_LTD_BEFORE, HAS_LTD_AFTER, ENROLLED_LTD_BEFORE, ENROLLED_LTD_AFTER, MRR_LTD_BEFORE, MRR_LTD_AFTER,
  HAS_STD_BEFORE, HAS_STD_AFTER, ENROLLED_STD_BEFORE, ENROLLED_STD_AFTER, MRR_STD_BEFORE, MRR_STD_AFTER,
  HAS_FSA_BEFORE, HAS_FSA_AFTER, ENROLLED_FSA_BEFORE, ENROLLED_FSA_AFTER, MRR_FSA_BEFORE, MRR_FSA_AFTER,
  HAS_DCA_BEFORE, HAS_DCA_AFTER, ENROLLED_DCA_BEFORE, ENROLLED_DCA_AFTER, MRR_DCA_BEFORE, MRR_DCA_AFTER,
  HAS_HSA_BEFORE, HAS_HSA_AFTER, ENROLLED_HSA_BEFORE, ENROLLED_HSA_AFTER, MRR_HSA_BEFORE, MRR_HSA_AFTER,
  HAS_VLIFE_BEFORE, HAS_VLIFE_AFTER, ENROLLED_VLIFE_BEFORE, ENROLLED_VLIFE_AFTER, MRR_VLIFE_BEFORE, MRR_VLIFE_AFTER,
  HAS_VLTD_BEFORE,  HAS_VLTD_AFTER,  ENROLLED_VLTD_BEFORE,  ENROLLED_VLTD_AFTER,  MRR_VLTD_BEFORE,  MRR_VLTD_AFTER,
  HAS_VSTD_BEFORE,  HAS_VSTD_AFTER,  ENROLLED_VSTD_BEFORE,  ENROLLED_VSTD_AFTER,  MRR_VSTD_BEFORE,  MRR_VSTD_AFTER,
  TO_JSON(carrier_detail) AS CARRIER_DETAIL
FROM calc
WHERE INFERRED_CLOSE_DATE IS NOT NULL
  AND INFERRED_CLOSE_DATE BETWEEN '{{Close Start}}' AND '{{Close End}}'
ORDER BY INFERRED_CLOSE_DATE, SFDC_OBJECT_ID
