SELECT SFDC_OBJECT_ID, HI_RENEWAL_ID, ZP_COMPANY_ID, SFDC_ACCOUNT_ID,
  SFDC_OBJECT_NAME_OR_NUM, STATUS, TO_CHAR(RENEWAL_DATE,'YYYY-MM-DD') RENEWAL_DATE,
  OWNER_NAME, OWNER_ROLE, OPPORTUNITY_OWNER_PE_NAME AS PE, FUNDING_TYPE,
  STAGE_DETAIL, REASON_FOR_ADVISING, NEEDS_RECERTIFICATION, SPECIAL_ENROLLMENT, ADVISING_BLOCKED_REASON,
  TO_CHAR(LAST_STATUS_CHANGE_TS) LAST_STATUS_CHANGE_TS,
  ACTIVE_EMPLOYEES_BEFORE, BENEFITS_ELIGIBLE_EMPLOYEES_BEFORE, NUMBER_EMPLOYEES_ENROLLED_BEFORE,
  HAS_MEDICAL_BEFORE,
  DATEDIFF('day', CURRENT_DATE, RENEWAL_DATE) AS DAYS_TO_RENEWAL,
  DATEDIFF('day', LAST_STATUS_CHANGE_TS, CURRENT_DATE) AS DAYS_IN_STAGE,
  IFF(STATUS ILIKE '%closed won%' OR STATUS ILIKE '%closed lost%' OR STATUS ILIKE '%order lost%' OR STATUS ILIKE '%closed admin%', TRUE, FALSE) AS CLOSED,
  TO_CHAR(RENEWAL_DATE,'YYYY-MM') AS COHORT
FROM BI_REPORTING.ADVISING_OPPORTUNITIES
WHERE RENEWAL_DATE IN ({{cohort_dates}})
